package ProyectoFinal;

import sm.iyl.iu.Lienzo2D;

/**
 * Clase JInternalFrame que contiene el objeto Lienzo2D para pintar formas e imágenes
 * @author Ignacio Yuste López
 */
public class VentanaInternaImagen extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInterna
     */
    public VentanaInternaImagen() {
        initComponents();
        this.setSize(400,300);
        this.jScrollPane1.setSize(400,300);
     
    }

    /**
     * Método que devuelve el Lienzo2D de la ventana interna
     * @return Lienzo2D de la ventana interna
     */
    public Lienzo2D getLienzo2D() {
        return lienzo2D;
    }

    /**
     * Método que establece un Lienzo2D a la ventana interna
     * @param lienzo2D Lienzo2D a establecer
     */
    public void setLienzo2D(Lienzo2D lienzo2D) {
        this.lienzo2D = lienzo2D;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2D = new sm.iyl.iu.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(50, 50));
        setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2D);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.iyl.iu.Lienzo2D lienzo2D;
    // End of variables declaration//GEN-END:variables
}
